/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExchangeRouteImport } from './routes/_authenticated/exchange'
import { Route as AuthenticatedItemsRouteImport } from './routes/_authenticated/items'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedLexiconRouteImport } from './routes/_authenticated/lexicon'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as ApiPublicTmpExchangeTestRouteImport } from './routes/api/public/tmp-exchange-test'
import { Route as ApiPublicV1ItemsRouteImport } from './routes/api/public/v1/items'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExchangeRoute = AuthenticatedExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsRoute = AuthenticatedItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLexiconRoute = AuthenticatedLexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTmpExchangeTestRoute =
  ApiPublicTmpExchangeTestRouteImport.update({
    id: '/api/public/tmp-exchange-test',
    path: '/api/public/tmp-exchange-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ItemsRoute = ApiPublicV1ItemsRouteImport.update({
  id: '/api/public/v1/items',
  path: '/api/public/v1/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchange': typeof AuthenticatedExchangeRoute
  '/items': typeof AuthenticatedItemsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/lexicon': typeof AuthenticatedLexiconRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/api/public/tmp-exchange-test': typeof ApiPublicTmpExchangeTestRoute
  '/api/public/v1/items': typeof ApiPublicV1ItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exchange': typeof AuthenticatedExchangeRoute
  '/items': typeof AuthenticatedItemsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/lexicon': typeof AuthenticatedLexiconRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/api/public/tmp-exchange-test': typeof ApiPublicTmpExchangeTestRoute
  '/api/public/v1/items': typeof ApiPublicV1ItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exchange': typeof AuthenticatedExchangeRoute
  '/_authenticated/items': typeof AuthenticatedItemsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/lexicon': typeof AuthenticatedLexiconRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/api/public/tmp-exchange-test': typeof ApiPublicTmpExchangeTestRoute
  '/api/public/v1/items': typeof ApiPublicV1ItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/exchange'
    | '/items'
    | '/jobs'
    | '/keys'
    | '/lexicon'
    | '/sources'
    | '/api/public/tmp-exchange-test'
    | '/api/public/v1/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/audit'
    | '/dashboard'
    | '/exchange'
    | '/items'
    | '/jobs'
    | '/keys'
    | '/lexicon'
    | '/sources'
    | '/api/public/tmp-exchange-test'
    | '/api/public/v1/items'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/audit'
    | '/_authenticated/dashboard'
    | '/_authenticated/exchange'
    | '/_authenticated/items'
    | '/_authenticated/jobs'
    | '/_authenticated/keys'
    | '/_authenticated/lexicon'
    | '/_authenticated/sources'
    | '/api/public/tmp-exchange-test'
    | '/api/public/v1/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTmpExchangeTestRoute: typeof ApiPublicTmpExchangeTestRoute
  ApiPublicV1ItemsRoute: typeof ApiPublicV1ItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exchange': {
      id: '/_authenticated/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof AuthenticatedExchangeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items': {
      id: '/_authenticated/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lexicon': {
      id: '/_authenticated/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof AuthenticatedLexiconRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/tmp-exchange-test': {
      id: '/api/public/tmp-exchange-test'
      path: '/api/public/tmp-exchange-test'
      fullPath: '/api/public/tmp-exchange-test'
      preLoaderRoute: typeof ApiPublicTmpExchangeTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/items': {
      id: '/api/public/v1/items'
      path: '/api/public/v1/items'
      fullPath: '/api/public/v1/items'
      preLoaderRoute: typeof ApiPublicV1ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExchangeRoute: typeof AuthenticatedExchangeRoute
  AuthenticatedItemsRoute: typeof AuthenticatedItemsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLexiconRoute: typeof AuthenticatedLexiconRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExchangeRoute: AuthenticatedExchangeRoute,
  AuthenticatedItemsRoute: AuthenticatedItemsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLexiconRoute: AuthenticatedLexiconRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTmpExchangeTestRoute: ApiPublicTmpExchangeTestRoute,
  ApiPublicV1ItemsRoute: ApiPublicV1ItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
